# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:10
    # working_directory: /tmp

jobs:
  setup:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Dependency Installation
          command: npm install
      - persist_to_workspace:
          root: ~/
          paths:
            - project/*
        
  tests: 
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Lint
          command: npm run lint:ci
      - run:
          name: Tests
          command: npm run test:ci
          environment:
            JEST_JUNIT_OUTPUT: "reports/jest/results.xml"
      - store_artifacts:
          path: reports
          destination: reports
      - store_test_results:
          path: reports
  build:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Build
          command: npm run build
      - store_artifacts:
          path: dist
          prefix: dist


  # # tests:
  # #   steps:

  # build:
  #   docker:
  #     # specify the version you desire here
  #     - image: circleci/node:10

  #     # Specify service dependencies here if necessary
  #     # CircleCI maintains a library of pre-built images
  #     # documented at https://circleci.com/docs/2.0/circleci-images/
  #     # - image: circleci/mongo:3.4.4

  #   # working_directory: ~/repo

  #   steps:
  #     - checkout

  #     # Download and cache dependencies
  #   #   - restore_cache:
  #   #       keys:
  #   #         - v1-dependencies-{{ checksum "package.json" }}
  #   #         # fallback to using the latest cache if no exact match is found
  #   #         - v1-dependencies-

  #     - run:
  #       name: Dependency Installation
  #       command: npm install

  #     - run:
  #       name: Tests
  #       command: npm test

  #     # - save_cache:
  #     #     paths:
  #     #       - node_modules
  #     #     key: v1-dependencies-{{ checksum "package.json" }}

  #     # # run tests!
  #     # - run: yarn test

workflows:
  version: 2
  build_and_test:
    jobs:
      - setup
      - tests:
          requires:
            - setup
      - build:
          requires:
            - tests